### ISSUE TITLE
Doesn't change prompt colors

### ISSUE THREAD

**Issue by ghost** [ramnes/context-color#4]
```
$ context-color -c 'echo hi'

$ context-color -c "date" -p
\[\]
```

Running `export PS1="$(context-color -p)$PS1\[\e[0m\]"` does not seem to change my current prompt colors. From the README, I thought it would change them immediately. I'm not really sure why it didn't.

GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
 Ubuntu 17.10

**Comment by ramnes** [comment]
What happens if you run `echo "$(context-color)foo"` ?

What's your current PS1?

**Comment by ghost** [comment]
Running that command, `foo` appears in blue.

PS1 is `\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$`

**Comment by ramnes** [comment]
So yeah, it's just that your current PS1 is full of sequences that prevent the example in the README to work. :wink: 

In your case, you have to modify your prompt directly. For example: `export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01m\]$(context-color -p)\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$"`

**Comment by ghost** [comment]
Great, thanks!
