### ISSUE TITLE
Disallow certain colors

### ISSUE THREAD

**Issue by ghost** [ramnes/context-color#5]
I use black backgrounds, but it's possible to get black foreground context colors, which makes text hard to read. Is it possible to avoid black?

**Comment by ramnes** [comment]
This is indeed a good feature idea, as well as the opposite (only use some given colors). I've started to think about it but I'm not sure yet on how I would implement it. Contributions welcome!

**Comment by ramnes** [comment]
Work in progress in the [`deny-colors`](https://github.com/ramnes/context-color/tree/deny-colors) branch.

**Comment by ramnes** [comment]
If you have a 256 colors terminal and wish to remove all black colors, you can now use the `--exclude/-e` flag, for example like this: `context-color -e 0,16,232`.

Cheers!
