### ISSUE TITLE
Overlaping long command line

### ISSUE THREAD

**Issue by lucgiffon** [ramnes/context-color#8]
Hello,
I've experienced an issue that I didn't notice first:
When using the classic $(context-color) command for customizing my prompt like this:
```
PS1='[\d \A] \[\e[31m\]\u\[\e[0m\]@\[\e[0m\]$(context-color -c hostname)\h\[\e[0m\]:\w\\$ '
```
The prompt always used 1 line for big command lines; E.g long lines are wrapped around themselves, meaning that the new line overlaps the previous one. So the terminal wasn't usable anymore.

I figured this was a classic issue with PS1 customization and it is because the colour code wasn't wrapped inside brackets as in `\[\e[31m\]` where the colour code `\e[31m` is wrapped inside `\[ \]`. So to sort this problem out I just changed `$(context-color -c hostname)` to `\[$(context-color -c hostname)\]` and it worked fine.

I don't know if this is normal and expected behavior?

**Comment by ramnes** [comment]
Just add the `-p` flag to your `context-color` command. It is there exactly for this purpose. :wink:

**Comment by ramnes** [comment]
I've added a small notice about this on https://github.com/ramnes/context-color/commit/39b2989eed5468c04dc277584d13704abad4496f. Thank you!

**Comment by lucgiffon** [comment]
Hmm actually I first thought the `-p` option was done on this purpose but when I add it, I get the following prompt: 
```
[jeu. août 16 16:21] luc@\[\]everest:~$
```
the colouring is good but I have the `\[\]` which is not. Plus, the main issue (overlapping lines) is not solved with the -p option. Here is the PS1 config I use to get the above output:
```
PS1='[\d \A] \[\e[32m\]\u\[\e[0m\]@$(context-color -p -c hostname)\h\[\e[0m\]:\w\\$ '
```

**Comment by ramnes** [comment]
What shell are you using?

**Comment by ramnes** [comment]
Alright, I get it: just put double quotes rather than single quotes (and keep the `-p`). :wink:

**Comment by lucgiffon** [comment]
I am using bash with the KDE Konsole terminal on Kubuntu.

**Comment by lucgiffon** [comment]
oh, s***, i'm not used to bash. I didn't know this difference. Thank you.

**Comment by ramnes** [comment]
What happens with single quotes is that `$(context-color)` is not evaluated at the PS1 definition time, but each time the variable is used. But the `\[\]` notation that `context-color` uses to avoid the line wrap problem is only valid at definition time. 

So yeah, you should either put double quotes and have it evaluated once, or if you really need to be evaluated each time, use `$PROMPT_COMMAND` or throw some `\[\]` around it with single quotes.

Reopening so that I document this on the README later.
